spring.application.name=tarefas
jwt.secret=${JWT_SECRET}

# Define o fuso horário que o Jackson usará para serializar/desserializar
spring.jackson.time-zone=America/Sao_Paulo

# (Opcional) Garante que o formato de data padrão siga o seu pattern
spring.jackson.date-format=dd-MM-yyyy HH:mm:ss

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/db_agendador

# URL do microserviço de usuário (COM http://)
usuario.url=http://localhost:8080

# Porta do serviço de tarefas
server.port=8081

# Logs
logging.level.com.projetozero=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
