spring.application.name=tarefas
jwt.secret=${JWT_SECRET}

spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.date-format=dd-MM-yyyy HH:mm:ss

spring.data.mongodb.uri=${MONGODB_URI}

usuario.url=${USUARIO_URL}

server.port=8081

logging.level.com.projetozero=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG